-- 12. Find the total revenue generated by each employee
SELECT e.employee_id, e.first_name, e.last_name, SUM(od.quantity * p.unit_price * (1 - od.discount)) AS total_revenue
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id
JOIN order_details od ON o.order_id = od.order_id
JOIN products p ON od.product_id = p.product_id
GROUP BY e.employee_id, e.first_name, e.last_name;